### ISSUE TITLE
rake aborted - no such file or directory, /WebBlocks/package/jquery/dist/jquery.min.js

### ISSUE THREAD

**Issue by peterm95018** [ucla-oarc-web/WebBlocks#106]
I've seen this error on two different machines today.

It appears that bundle is creating the directory, but failing to grab the jquery.min.js source file.

When I go grab the file and place it at /WebBlocks/package/jquery/dist/ and re-run bundle, I get a successful build.

Peter

**Comment by loganfranken** [comment]
At least for me, this was the error resulting from the issue discussed in the last two comments of #76 (jQuery has `git://` submodule references). I was able to resolve this with the following process (I'm assuming one or more of these steps is actually unnecessary):

Change `git://` to `https://` in:

```
WebBlocks\.git\modules\package\jquery\config
WebBlocks\.git\modules\package\jquery\modules\src\sizzle\config
WebBlocks\package\jquery\.gitmodules
```

Then hop over to the `WebBlocks\package\jquery` directory and run the following:

```
git submodule update
node ./node_modules/grunt/bin/grunt
```

**Comment by ebollens** [comment]
While fetching a copy of the jquery.min.js file solves the problem in one case, I'd like to see if we can't figure out what's actually preventing jQuery from compiling. Basically, jQuery gets some submodules, runs NPM to install some packages, and then calls Grunt. Do we know what part of the process to do this is failing exactly?

In line with @loganfranken's question, are you sure you were able to fetch the submodules so that Grunt could be called?

The ultimate bummer here is that the jQuery submodule does not actually include a built copy of jQuery, but rather it has to build it using Grunt. I may take a look at how Bower does this, and maybe we can even use that to get around issues like this (see #104 thanks to @ilessing)

**Comment by peterm95018** [comment]
I recreated a WebBlocks install to see if I could determine at which step the process fails.
At the rake step, it appears that grunt is installed at 
/WebBlocks/package/jquery/node_modules/grunt  
but the
/WebBlocks/package/jquery/dist directory is empty.

per @loganfranken, I've changed git:// to https:// at 
/WebBlocks\package\jquery.gitmodules.
The file, WebBlocks.git\modules\package\jquery\config was already correct.
This path didn't exist, WebBlocks.git\modules\package\jquery\modules\src\sizzle\config
I didn't submodule update, since that was there.

And now, I'll go read the md help file so I can format my responses correctly.

**Comment by ebollens** [comment]
Could it be that Grunt isn't getting called? That's where the `dist` directory is built from.

The call that WebBlocks tries to use by default:

```
node ./node_modules/grunt/bin/grunt
```

Does this call work when you're in the `package/jquery` directory?

**Comment by peterm95018** [comment]
cd `package/jquery`

```
node ./node_modules/grunt/bin/grunt
```

aborts with error:

```
path.existsSync is now called `fs.existsSync`.
Running "submodules" task


Running "selector:src/selector.js" (selector) task
<WARN> Unable to read "src/sizzle/sizzle.js" file (Error code: ENOENT). Use --force to continue. </WARN>

Aborted due to warnings.
```

re-ran with `--force`
`dist/jquery.min.js` has now arrived.

wiped out WebBlocks, rinse, lather, repeat. same result

**Comment by ebollens** [comment]
@peterm95018 looks like I may have tracked down what could be causing this... Lemme put together a commit.

**Comment by ebollens** [comment]
@peterm95018 please update to 5d2f11c and let me know if that resolves the problem.

**Comment by ebollens** [comment]
@peterm95018 please clarify if this solved the problem.

**Comment by daryl-williams** [comment]
While building a clean install of WebBlocks I got this error today, Tue. Oct.16. I have verified that the rake/build/package/jquery.rb file has the 5d2f11c patch.

**Comment by ebollens** [comment]
Hmmm, it appears that this is being caused by the following error:

```
[L8467:C50] Value of '_' may be overwritten in IE.
                  } catch( _ ) {
```

I tried updating to a later version of jQuery, hoping they had solved the problem, but unfortunately it looks like it persists as late as jQuery 1.8.2, the latest release version. That said, jQuery pretty much isn't building nicely with its own build tools, so we are going to need to look at using the `--force` flag by default to ignore the warning and still actually build jQuery.

Please pull up to the latest revision c798796 and let me know if that solves the problem. If not, reopen this issue again.

**Comment by daryl-williams** [comment]
I just did another pull of the repository and am still getting the same problem. The pull reported:

From github.com:ucla/WebBlocks
- branch            master     -> FETCH_HEAD
  Updating 7fdf7b2..c798796
  Fast-forward
  doc/Configuration.md |    2 +-
  rake/config.rb       |    2 +-
  2 files changed, 2 insertions(+), 2 deletions(-)

and the rake:

[Rakefile] init
[Rakefile] build
  [Builder] Setting up temporary build region
  [Builder: jQuery] Managing jQuery submodule
  [Builder: jQuery] Packaging jQuery into Core JS file
rake aborted!
No such file or directory - /var/www/sites/wba/htdocs/package/jquery/dist/jquery.min.js

Please let me know if I can provide more information.

**Comment by ebollens** [comment]
Reopening this as it was mentioned in #130 as a regression failure.

**Comment by ebollens** [comment]
As reference, the command this is using is:

```
node ./node_modules/grunt/bin/grunt --force
```

@loganfranken @brendanmurphy if you delete your `dist` directory and then invoke that command from within the `package/jquery` directory, does it work?

**Comment by loganfranken** [comment]
Hey @ebollens, sorry for the wait. I'm running Windows 7 and I had to do two things to get this up and running:
1. Execute `npm install` from the `package/jquery` directory
2. Execute the `node` command you pasted above from that directory as well

Running `rake` after step 1 still gave the same error.

**Comment by ebollens** [comment]
I'm confused, because `rake` runs that command...

**Comment by ebollens** [comment]
It just dawned on me that the problem might be that it's not doing an init/update on the submodules within the submodule.

**Comment by ebollens** [comment]
I realize that right now, we don't make an npm call within the jQuery repo. This might be part of the problem. I'll tinker with this tomorrow.

**Comment by ebollens** [comment]
Just filed another commit that might have solved this problem.

**Comment by ebollens** [comment]
Guess what's broken? This one again.

**Comment by ebollens** [comment]
Here's the stack trace:

```
[Dispatcher] Executing task: compile
  [Package: jQuery] Compiling jQuery
    [Builder: jQuery] NPM execution failed
rake aborted!
NPM execution failed
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:48:in `failure'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Package/Jquery.rb:48:in `compile_js'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Package/Jquery.rb:46:in `chdir'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Package/Jquery.rb:46:in `compile_js'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:40:in `task'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:87:in `scope'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:39:in `task'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Package/Jquery.rb:45:in `compile_js'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Package/Jquery.rb:37:in `compile'
./lib/Build/Dispatcher.rb:33:in `send'
./lib/Build/Dispatcher.rb:33:in `execute'
./lib/Build/Dispatcher.rb:32:in `each'
./lib/Build/Dispatcher.rb:32:in `execute'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:40:in `task'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:87:in `scope'
/Applications/MAMP/htdocs/WebBlocks/lib/Build/Adapter/../../Logger.rb:39:in `task'
./lib/Build/Dispatcher.rb:31:in `execute'
./lib/Build/Dispatcher.rb:30:in `each'
./lib/Build/Dispatcher.rb:30:in `execute'
./build.rb:13
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
Tasks: TOP => default => build
```

**Comment by ebollens** [comment]
Here's the error log:

```
npm http GET https://registry.npmjs.org/grunt-compare-size
npm http 304 https://registry.npmjs.org/grunt-compare-size
npm http GET https://registry.npmjs.org/gzip-js
npm http GET https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/gzip-js
npm http 304 https://registry.npmjs.org/grunt
npm ERR! error installing grunt-compare-size@0.3.1

npm ERR! Error: No compatible version found: grunt@'>=0.4.0rc3 <0.5.0-'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.2.15","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.8","0.3.9","0.3.10","0.3.11","0.3.12","0.3.13a","0.3.13","0.3.14","0.3.15","0.3.16","0.3.17"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/local/lib/node_modules/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:415:44)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:408:5
npm ERR!     at Object.saved [as oncomplete] (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Applications/MAMP/htdocs/WebBlocks/package/jquery
npm ERR! node -v v0.6.7
npm ERR! npm -v 1.1.0
npm ERR! message No compatible version found: grunt@'>=0.4.0rc3 <0.5.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.2.15","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.8","0.3.9","0.3.10","0.3.11","0.3.12","0.3.13a","0.3.13","0.3.14","0.3.15","0.3.16","0.3.17"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/MAMP/htdocs/WebBlocks/package/jquery/npm-debug.log
npm not ok
```

**Comment by ebollens** [comment]
Compatibility problem was being caused by too old a version of NPM.

I've resolved this by using https://github.com/visionmedia/n to change the version of Node to a more recent one.

However, now I'm getting a problem with installing `grunt-compare-size`:

```

$ npm install grunt-compare-size
npm http GET https://registry.npmjs.org/grunt-compare-size
npm http 304 https://registry.npmjs.org/grunt-compare-size
npm http GET https://registry.npmjs.org/gzip-js
npm http GET https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/gzip-js
npm http 304 https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/deflate-js
npm http GET https://registry.npmjs.org/crc32
npm http 304 https://registry.npmjs.org/deflate-js
npm http 304 https://registry.npmjs.org/crc32
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/hooker
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/eventemitter2
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore
npm ERR! error installing js-yaml@1.0.3
npm ERR! error installing grunt@0.4.0rc4
npm ERR! error installing grunt-compare-size@0.3.1

npm ERR! Error: ENOENT, chmod '/Applications/MAMP/htdocs/WebBlocks/package/jquery/node_modules/grunt-compare-size/node_modules/grunt/node_modules/js-yaml/bin/js-yaml.js'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt-compare-size"
npm ERR! cwd /Applications/MAMP/htdocs/WebBlocks/package/jquery
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.0
npm ERR! path /Applications/MAMP/htdocs/WebBlocks/package/jquery/node_modules/grunt-compare-size/node_modules/grunt/node_modules/js-yaml/bin/js-yaml.js
npm ERR! code ENOENT
npm ERR! message ENOENT, chmod '/Applications/MAMP/htdocs/WebBlocks/package/jquery/node_modules/grunt-compare-size/node_modules/grunt/node_modules/js-yaml/bin/js-yaml.js'
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/MAMP/htdocs/WebBlocks/package/jquery/npm-debug.log
npm not ok
```

**Comment by ebollens** [comment]
Actually building jQuery live is proving such a nightmare, my workaround is going to be to download a copy of jQuery as distributed from jquery.com rather than actually run the compiler. This is a workaround for the time being, although eventually we want to move back to a compile process for jquery.
