### ISSUE TITLE
Unit Test test_link_sass_libs_for Fails on RHEL6

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#161]
The `test_link_sass_lib_for` test fails on RHEL6 but not Darwin:

```
TypeError: can't convert false into String
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:215:in `initialize'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:215:in `open'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:215:in `link_sass_lib'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:225:in `link_sass_libs_for'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:108:in `sass_libs_for'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:106:in `each'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:106:in `sass_libs_for'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:224:in `link_sass_libs_for'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/test/unit/Module.rb:120:in `test_link_sass_libs_for'
```

**Comment by ebollens** [comment]
This seems to be resolved now - curtesy of #160.
