### ISSUE TITLE
Unit Test test_link_sass_lib Fails on RHEL6

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#162]
The `test_link_sass_lib` test fails on RHEL6 but not Darwin:

```
TypeError: can't convert false into String
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:215:in `initialize'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:215:in `open'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/lib/Build/Adapter/../Module.rb:215:in `link_sass_lib'
    /var/lib/jenkins/jobs/WebBlocks Build Tests/workspace/test/unit/Module.rb:103:in `test_link_sass_lib'
```

**Comment by ebollens** [comment]
This seems to be resolved now - curtesy of #160.
