### ISSUE TITLE
Unit Tests Failing in Windows 7

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#204]
```
  1) Failure:
test_link_sass_lib(TestUnitModule)
    [C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:75:in `assert_file_has_pattern'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:105:in `assert_file_has_import_rule'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/Module.rb:104:in `test_link_sass_lib']:
Add include to _WebBlocks-variables.scss.
<nil> expected to not be nil.

  2) Failure:
test_link_sass_libs_for(TestUnitModule)
    [C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:75:in `assert_file_has_pattern'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:105:in `assert_file_has_import_rule'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/Module.rb:122:in `test_link_sass_libs_for']:
Import set for regular SASS lib.
<nil> expected to not be nil.

  3) Failure:
test_append_file(TestUnitUtilities)
    [C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:75:in `assert_file_has_pattern'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/Utilities.rb:33:in `test_append_file']:
Initial setup of file.
<nil> expected to not be nil.

  4) Failure:
test_link_css(TestUnitWebBlocks)
    [C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:75:in `assert_file_has_pattern'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/../../lib/Test.rb:105:in `assert_file_has_import_rule'
     C:/xampp/htdocs/d7base/sites/all/themes/webblocks/package/WebBlocks/test/unit/WebBlocks.rb:74:in `test_link_css']:
Import rule set for variables in SASS directory to _WebBlocks-variables.scss.
<nil> expected to not be nil.
```

/FROM @ebollens

**Comment by lnicks** [comment]
The fix for error (3) has to do with whitespace issues:

``` ruby
  def test_append_file

    file_create "#{@dir}/1", "1"
    file_create "#{@dir}/2", "2"

    assert_file_has_pattern "#{@dir}/1", /^1\s*$/, "Initial setup of file"
    assert_file_has_pattern "#{@dir}/2", /^2\s*$/, "Initial setup of file"

    append_file "#{@dir}/2", "#{@dir}/1"

    assert_file_has_pattern "#{@dir}/1", /^1\s*2\s*$/, "File appended"
    assert_file_has_pattern "#{@dir}/2", /^2\s*$/, "No side-effects during append"

  end
```

/FROM @ebollens

**Comment by lnicks** [comment]
The fix for the other three is this:

``` ruby
        def assert_file_has_import_rule file, rule, message = ''

          assert_file_has_pattern file, /\@import "#{Regexp.escape(rule)}";/, message

        end
```

Luckily, none of these are actually WebBlocks compiler bugs but rather problems in the unit tests themselves.

/FROM @ebollens
