### ISSUE TITLE
Barebones compiler issue

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#352]
Referencing Issue 137 from `drupal-WebBlocks`.

```
c:\xampp\htdocs>git clone https://github.com/ucla/WebBlocks.git wbxOnly
Cloning into 'wbxOnly'...
remote: Counting objects: 5427, done.
remote: Compressing objects: 100% (2208/2208), done.
Rremote: Total 5427 (delta 2893), reused 5285 (deleceiving objects:  98% (5319/54
Receiving objects: 100% (5427/5427), 864.12 KiB | 194 KiB/s, done.
Resolving deltas: 100% (2893/2893), done.

c:\xampp\htdocs>cd wbxonly

c:\xampp\htdocs\wbxOnly>rake
[Dispatcher] Executing task: before_init
[Dispatcher] Executing task: init
[Dispatcher] Executing task: after_init
[Dispatcher] Executing task: before_preprocess
[Dispatcher] Executing task: preprocess
[Dispatcher] Executing task: after_preprocess
[Dispatcher] Executing task: before_link
[Dispatcher] Executing task: link
[Dispatcher] Executing task: after_link
[Dispatcher] Executing task: before_compile
[Dispatcher] Executing task: compile
[Dispatcher] Executing task: after_compile
[Dispatcher] Executing task: before_assemble
[Dispatcher] Executing task: assemble
[Dispatcher] Executing task: after_assemble
[Dispatcher] Executing task: before_package
[Dispatcher] Executing task: package
rake aborted!
Compression error encountered in c:/xampp/htdocs/wbxOnly/.build-tmp/js/blocks.js
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:58:in `failure'
c:/xampp/htdocs/wbxOnly/lib/Build/WebBlocks.rb:317:in `package_js'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:75:in `info'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:97:in `scope'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:74:in `info'
c:/xampp/htdocs/wbxOnly/lib/Build/WebBlocks.rb:313:in `package_js'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:50:in `task'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:97:in `scope'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:49:in `task'
c:/xampp/htdocs/wbxOnly/lib/Build/WebBlocks.rb:311:in `package_js'
c:/xampp/htdocs/wbxOnly/lib/Build/WebBlocks.rb:257:in `package'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:50:in `task'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:97:in `scope'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:49:in `task'
c:/xampp/htdocs/wbxOnly/lib/Build/WebBlocks.rb:253:in `package'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:44:in `send'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:44:in `execute'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:42:in `each'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:42:in `execute'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:44:in `system'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:97:in `scope'
c:/xampp/htdocs/wbxOnly/lib/Build/Adapter/../../Logger.rb:43:in `system'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:39:in `execute'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:38:in `each'
c:/xampp/htdocs/wbxOnly/lib/Build/Dispatcher.rb:38:in `execute'
c:/xampp/htdocs/wbxOnly/lib/Rake/Task/build.rb:20
Tasks: TOP => default => build
(See full trace by running task with --trace)

c:\xampp\htdocs\wbxOnly>
```

/cc @ebollens @chris4ucla

**Comment by ebollens** [comment]
This has nothing to do with the error you reported in `drupal-WebBlocks`. That was about a deprecation error:

> DEPRECATION WARNING on line 62 of c:/xampp/htdocs/dent/sites/all/themes/dentistry/src/sass/megaMenu.scss:
>  @extending an outer selector from within @media is deprecated.
>  You may only @extend selectors within the same directive.
>  This will be an error in Sass 3.3.
>  It can only work once @extend is supported natively in the browser

This is about a compression error, which means with uglifyjs/uglifycss.

Can you confirm that you called `npm install` and that uglifyjs and uglifycss are actually there? That's the most frequent reason to hit this error (it's documented in the "Troubleshooting" section of the documentation).

**Comment by lnicks** [comment]
Right. Posted here as an effort to document the results of the suggested test (assumed you would want to know and the right repo).  Didn't do any troubleshooting, since it didn't appear to be related.  My apologies!

You're correct, `npm install` fixed it.

/cc @chris4ucla
