### ISSUE TITLE
Rake aborts with CSS Split enabled

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#425]
I am having some problems with the compiler.  I've added the two lines of text into `rakefile.rb` to enable CSS Splitting, and this is what I get when I run `rake`.

````Using rake (10.0.3)
Using chunky_png (1.2.7)
Using fssm (0.2.9)
Using sass (3.2.5)
Using compass (0.12.2)
Using extensions (0.6.0)
Using rb-fsevent (0.9.3)
Using systemu (2.5.2)
Using bundler (1.2.3)
Your bundle is complete! Use`bundle show [gemname]`to see where a bundled gem
is installed.
npm install
rake  -- --config=c:/xampp/htdocs/dent/sites/all/themes/dentistry/Rakefile-config.rb
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Package/../Utilities.rb:84: warning: already initialized constant BUNDLER_VARS
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Core/../Utilities.rb:84: warning: already initialized constant BUNDLER_VARS
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../Utilities.rb:84: warning: already initialized constant BUNDLER_VARS
[Dispatcher] Executing task: before_init
[Dispatcher] Executing task: init
[Dispatcher] Executing task: after_init
[Dispatcher] Executing task: before_preprocess
[Dispatcher] Executing task: preprocess
rake aborted!
Initialization failed for submodules of submodule opticss
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:58:in`failure'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../Submodule.rb:58:in `init_submodule_submodules'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../Submodule.rb:53:in`chdir'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../Submodule.rb:53:in `init_submodule_submodules'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:50:in`task'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:97:in `scope'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:49:in`task'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../Submodule.rb:51:in `init_submodule_submodules'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../Submodule.rb:131:in`preprocess_submodule_submodules'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Package/Opticss.rb:37:in `preprocess_css'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Package/Opticss.rb:25:in`preprocess'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:44:in `send'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:44:in`execute'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:42:in `each'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:42:in`execute'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:44:in `system'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:97:in`scope'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Adapter/../../Logger.rb:43:in `system'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:39:in`execute'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:38:in `each'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Build/Dispatcher.rb:38:in`execute'
c:/xampp/htdocs/dent/sites/all/themes/webblocks/package/WebBlocks/lib/Rake/Task/build.rb:6
Tasks: TOP => default => build
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake  -- --config=c:/xampp/htdocs/dent/sit...]
c:/xampp/htdocs/dent/sites/all/themes/dentistry/Rakefile:34:in `rake'
c:/xampp/htdocs/dent/sites/all/themes/dentistry/Rakefile:33:in`chdir'
c:/xampp/htdocs/dent/sites/all/themes/dentistry/Rakefile:33:in `rake'
c:/xampp/htdocs/dent/sites/all/themes/dentistry/Rakefile:51
Tasks: TOP => default
(See full trace by running task with --trace)

```
@ebollens @chris4ucla 
```

**Comment by lnicks** [comment]
Here's my rakefile:

```
require 'pathname'
theme_dir = File.dirname(Pathname.new(__FILE__).realpath)
base_theme_dir = "#{File.dirname theme_dir}/webblocks"

# The directory into which WebBlocks is built
WebBlocks.config[:build][:dir] = "#{theme_dir}/assets"

# The directory where sources for the build are located
WebBlocks.config[:src][:dir] = "#{theme_dir}/src"

# Location of WebBlocks core components (config.rb, definitions, core adapter)
WebBlocks.config[:src][:core][:dir] = "#{base_theme_dir}/package/WebBlocks/src/core"

# Location of WebBlocks adapters
WebBlocks.config[:src][:adapters][:dir] = "#{base_theme_dir}/package/WebBlocks/src/adapter"

# Adapter packaged with WebBlocks
WebBlocks.config[:src][:adapter] = ['bootstrap']

# WebBlocks-Drupal base extension
WebBlocks.config[:src][:extensions] = []
#WebBlocks.config[:src][:extensions] << "#{base_theme_dir}/src/extension"
#WebBlocks.config[:src][:extensions] << "#{theme_dir}/src/extension"

# Packages compiled into WebBlocks
WebBlocks.config[:build][:packages]  = []
WebBlocks.config[:build][:packages] << :jquery # already included by Drupal
WebBlocks.config[:build][:packages] << :modernizr
WebBlocks.config[:build][:packages] << :respond
WebBlocks.config[:build][:packages] << :selectivizr
WebBlocks.config[:build][:packages] << :efx
WebBlocks.config[:build][:packages] << :opticss unless
WebBlocks.config[:build][:packages].include? :opticss

```

**Comment by ebollens** [comment]
Can you give me some details about the Git submodule for OptiCSS:
1. Is it in your packages folder at all?
2. Can you run `git submodule init`?
3. Can you run `git submodule update`?

**Comment by lnicks** [comment]
1. It is not
2. 2 & 3: They both run but nothing happens (which I assume is because its up to date).

**Comment by ebollens** [comment]
Can you plese run `git log` and provide the most recent commit ID; additionally, please provide what's in `.gitmodules` within the WebBlocks directory.

**Comment by lnicks** [comment]
Most recent commit

```
commit b17c706f2404ac65a4e1bd02c1c81593067c49e6
Merge: 5033ad4 8b7672b
Author: lnicks <lnicks@oit.ucla.edu>
Date:   Tue Jul 9 16:25:56 2013 -0700

    Merge branch 'master' of https://github.com/ucla/drupal-WebBlocks
```

```
[submodule "package/modernizr"]
    path = package/modernizr
    url = https://github.com/Modernizr/Modernizr.git
[submodule "package/selectivizr"]
    path = package/selectivizr
    url = https://github.com/keithclark/selectivizr.git
[submodule "package/respond"]
    path = package/respond
    url = https://github.com/scottjehl/Respond.git
[submodule "package/sass-twitter-bootstrap"]
    path = package/sass-twitter-bootstrap
    url = https://github.com/jlong/sass-twitter-bootstrap.git
[submodule "package/efx"]
    path = package/efx
    url = https://github.com/ebollens/efx.git
[submodule "package/lettering"]
    path = package/lettering
    url = https://github.com/davatron5000/Lettering.js.git
[submodule "package/OptiCSS"]
    path = package/OptiCSS
    url = https://github.com/ebollens/OptiCSS.git
```

**Comment by ebollens** [comment]
@lnicks that doesn't help me from a WebBlocks perspective on the commit ID. I need to know the commit ID of the latest commit in the WebBlocks submodule - so navigate to that folder and then run `git log`.

**Comment by lnicks** [comment]
Thought so, but I figured with the explicit directions on the gitmodules, I'd stick to the main repo.  

Here's the webblocks one:

```
commit 5d50c370c8f709787b79e03015456022b29cba2c
Author: Eric Bollens <ebollens@ucla.edu>
Date:   Sat Jun 22 11:56:17 2013 -0700

    Update README.md for completed beta
```
